import { MILLISECOND, SECOND, MINUTE, HOUR } from "./lib/constants/time";

const ENABLE_FILE_SYSTEM_WATCHING = true;
const ENABLE_LOCAL_SERVER_WATCHING = false;

const NOTIF_MAX_COUNT = 8;
const NOTIF_BADGE_LIMIT = 10;

const DEFAULT_EXTENSION_OPTIONS = {
    loadAll: true,
    courseConflictHighlight: true,
    storeWaitlist: true,
};
const POPUP_FLASH_TIME = 200;

export { DEFAULT_EXTENSION_OPTIONS, POPUP_FLASH_TIME, NOTIF_MAX_COUNT, NOTIF_BADGE_LIMIT, ENABLE_FILE_SYSTEM_WATCHING, ENABLE_LOCAL_SERVER_WATCHING };
